#!/bin/bash
set -xe

# Update the system clock
# Use timedatectl(1) to ensure the system clock is accurate:
timedatectl set-ntp true

# edit /etc/pacman.d/mirrorlist
# Make a backup, grab the latest 50 us mirrors synced within 12 hours choosing fastest 6 mirrors
cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
reflector --country US --age 12 --latest 50 --sort rate --protocol https --save /etc/pacman.d/mirrorlist -n 6

# Install base system
pacstrap -K /mnt base linux linux-firmware iwd lvm2 reflector sudo base-devel git

genfstab -U /mnt >> /mnt/etc/fstab

# start setting up networking
# https://wiki.archlinux.org/title/Systemd-resolved
# Creating the /etc/resolv.conf symlink will not be possible while inside arch-chroot, since the file is bind-mounted from the outside system. Instead, create the symlink from outside the chroot.
ln -sf /run/systemd/resolve/stub-resolv.conf /mnt/etc/resolv.conf

# We download a run the rest of the script in the chroot
# curl "https://raw.githubusercontent.com/jplikesbikes/arch-install/master/base-install-chroot" --output /mnt/base-install-chroot
# chmod +x /mnt/base-install-chroot

cp base-install-chroot /mnt/
arch-chroot /mnt ./base-install-chroot
rm /mnt/base-install-chroot

# unmount partitions
umount -R /mnt

shutdown -t sec now

