#!/bin/bash

# Update the system clock
# Use timedatectl(1) to ensure the system clock is accurate:
timedatectl set-ntp true

# https://wiki.archlinux.org/index.php/Dm-crypt/Encrypting_an_entire_system#LVM_on_LUKS

gdisk /dev/sda
# 1 efi and boot - EF00 512mb
# `n` `enter` for new
# `enter` partition 1
# `enter` for next free sector
# `+512mb`
# `ef00`

# 2 dm-crypted partition with lvm in it (contains rootvol, swapvol and homevol) - 8E00 rest of disk
# `n` `enter` for new
# `enter` for partition 2
# `enter` for next free sector
# `enter` for rest of disk
# `8e00` for lvm

# save and write
# `w` `enter `Y`

#dm-crypt with lvm with / and /home
cryptsetup luksFormat /dev/sda2
cryptsetup open --type luks /dev/sda2 lvm

pvcreate /dev/mapper/lvm
vgcreate MyStorage /dev/mapper/lvm

echo "Enter rootvol size ex. 6GB"
read ROOTVOLSIZE
lvcreate -L $ROOTVOLSIZE MyStorage -n rootvol
lvcreate -l +100%FREE MyStorage -n homevol

# Chech the lvm setup
lvdisplay

mkfs.ext4 /dev/mapper/MyStorage-rootvol
mkfs.ext4 /dev/mapper/MyStorage-homevol

mount /dev/MyStorage/rootvol /mnt
mkdir /mnt/home
mount /dev/MyStorage/homevol /mnt/home


#no swap for now can add later as a swapfile https://wiki.archlinux.org/index.php/Swap
#Boot
mkfs.fat /dev/sda1
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot

#edit /etc/pacman.d/mirrorlist
# Make a backup, grab the current us mirrors, enable all us mirrors, choose the 6 fastest mirrors
cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
wget -O /etc/pacman.d/mirrorlist.us "https://www.archlinux.org/mirrorlist/?country=US"
sed -i 's/^#Server/Server/' /etc/pacman.d/mirrorlist.us
rankmirrors -n 6 /etc/pacman.d/mirrorlist.us > /etc/pacman.d/mirrorlist

# Install base system
pacstrap -i /mnt base

genfstab -U /mnt >> /mnt/etc/fstab

# This stops the script and jumps into the chroot
# @todo break the script up here
arch-chroot /mnt ./base-install-chroot

# unmount partitions
umount -R /mnt

reboot

