#!/bin/bash

# Set the timezone
rm /etc/localtime
ln -s /usr/share/zoneinfo/America/New_York /etc/localtime
hwclock --systohc

# Set the hostname
echo "Enter Hostname"
read HOSTNAME
echo $HOSTNAME > /etc/hostname
echo "127.0.1.1	$HOSTNAME.localdomain	$HOSTNAME" >> /etc/hosts

# uncomment en_US.UTF-8
sed -i 's/^#en_US.UTF-8/en_US.UTF-8/' /etc/locale.gen
locale-gen

# Networking
# Using networkmanager
pacman -S iw wpa_supplicant dialog networkmanager dhclient
systemctl enable NetworkManager.service
# Using Systemd
# systemctrl enable systemd-networkd.service
# NETCTL=`networkctl list |grep -o "en\w*"`
#
# cat > /etc/systemd/network/50-wired.network << EOF
# [Match]
# Name=$NETCTL
#
# [Network]
# DHCP=yes
# EOF


# update MODULES='... dm_mod ...'
# update HOOKS='... keyboard encrypt lvm2 filesystem ...'
sed -i 's/^MODULES=""/MODULES="dm_mod"/' /etc/mkinitcpio.conf
sed -i 's/\(^HOOKS=".*\)keyboard\(.*$\)/\1\2/' /etc/mkinitcpio.conf
sed -i 's/\(^HOOKS=".*\)filesystems\(.*$\)/\1keyboard encrypt lvm2 filesystems\2/' /etc/mkinitcpio.conf

mkinitcpio -p linux
passwd

#### INTEL MICROCODE ####
#### Install the AUR package `systemd-boot-pacman-hook` to auto install new ucode updates into the boot partition
pacman -Syu --noconfirm intel-ucode

bootctl --path=/boot install
cat > /boot/loader/entries/arch.conf << EOF
title		Arch Linux
linux		/vmlinuz-linux
initrd		/intel-ucode.img
initrd		/initramfs-linux.img
options	cryptdevice=/dev/sda2:MyStorage root=/dev/mapper/MyStorage-rootvol
EOF

# exit the chroot
exit
