#!/bin/bash
set -xe

# Update the system clock
# Use timedatectl(1) to ensure the system clock is accurate:
timedatectl set-ntp true

# https://wiki.archlinux.org/index.php/Dm-crypt/Encrypting_an_entire_system#LVM_on_LUKS

gdisk /dev/sda
# 1 efi and boot - EF00 512mb
# `n` `enter` for new
# `enter` partition 1
# `enter` for next free sector
# `+512mb`
# `ef00`

# 2 dm-crypted partition with lvm in it (contains rootvol, swapvol and homevol) - 8E00 rest of disk
# `n` `enter` for new
# `enter` for partition 2
# `enter` for next free sector
# `enter` for rest of disk
# `8e00` for lvm

# save and write
# `w` `enter `Y`

#dm-crypt with lvm with / and /home
cryptsetup luksFormat /dev/sda2
cryptsetup open --type luks /dev/sda2 lvm

pvcreate /dev/mapper/lvm
vgcreate MyStorage /dev/mapper/lvm

echo "Enter rootvol size ex. 6GB"
read ROOTVOLSIZE
lvcreate -L $ROOTVOLSIZE MyStorage -n rootvol

echo "Enter varvol size ex. 1GB"
read VARVOLSIZE
lvcreate -L $VARVOLSIZE MyStorage -n varvol

lvcreate -l +100%FREE MyStorage -n homevol

# Chech the lvm setup
lvdisplay

mkfs.ext4 /dev/mapper/MyStorage-rootvol
mkfs.ext4 /dev/mapper/MyStorage-varvol
mkfs.ext4 /dev/mapper/MyStorage-homevol

mount /dev/MyStorage/rootvol /mnt
mkdir /mnt/var
mount /dev/MyStorage/varvol /mnt/var
# Because /var is its on partition this is known but safe error on shutdown
# https://bbs.archlinux.org/viewtopic.php?pid=1204644#p1204644
mkdir /mnt/home
mount /dev/MyStorage/homevol /mnt/home


# no swap for now can add later as a swapfile https://wiki.archlinux.org/index.php/Swap
# Boot
mkfs.fat /dev/sda1
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot

# edit /etc/pacman.d/mirrorlist
# Make a backup, grab the latest 50 us mirrors synced within 12 hours choosing fastest 6 mirrors
cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
reflector --country US --age 12 --latest 50 --sort rate --protocol https --save /etc/pacman.d/mirrorlist -n 6

# Install base system
pacstrap -K /mnt base linux linux-firmware iwd lvm2 reflector sudo base-devel git

genfstab -U /mnt >> /mnt/etc/fstab

# start setting up networking
# https://wiki.archlinux.org/title/Systemd-resolved
# Creating the /etc/resolv.conf symlink will not be possible while inside arch-chroot, since the file is bind-mounted from the outside system. Instead, create the symlink from outside the chroot.
ln -sf /run/systemd/resolve/stub-resolv.conf /mnt/etc/resolv.conf

# We download a run the rest of the script in the chroot
# curl "https://raw.githubusercontent.com/jplikesbikes/arch-install/master/base-install-chroot" --output /mnt/base-install-chroot
# chmod +x /mnt/base-install-chroot

cp base-install-chroot /mnt/
arch-chroot /mnt ./base-install-chroot

# unmount partitions
umount -R /mnt

shutdown -t sec now

